### ISSUE TITLE
Control (sub/superscript ) a single character or selected characters in a text field 

### ISSUE THREAD

**Issue by zachoverholser** [KevinGutowski/betterTypePanel#11]
Need the ability to change only selected text in a text field. Lets say I have "Test1" in a text field and I only want to superscript the "1" and keep the "Test" the same size. With your plugin I select only the "1" and it still superscripts the entire contents of the text field.

**Comment by KevinGutowski** [comment]
@zachoverholser I added this in with the 3.0 release a little while ago!
