### ISSUE TITLE
Pluggin not working on V53.2

### ISSUE THREAD

**Issue by jdearfriend** [KevinGutowski/betterTypePanel#19]
I just can't use it on my sketch Version 53.2. None of the option in the toggle window are actionnable.

**Comment by KevinGutowski** [comment]
Hiya @jdearfriend thanks for trying out the plugin. Sorry to hear that you are having troubles! Can you make sure that the font that you are selecting has the font font properties available? Try a font like Proxima Nova. I will work on supplying better messages when a font doesn’t support a particular feature.

It should definitely work in 53.2
<img width="928" alt="Screen Shot 2019-03-12 at 10 33 22 AM" src="https://user-images.githubusercontent.com/4199296/54222300-599f7280-44b2-11e9-8042-cc76b7a8d7c3.png">

**Comment by jdearfriend** [comment]
Hi Kevin,
Thank you for your feedback, it's the font properties that were not
available indeed, you're right. I tried Proxima, it works.
I'll keep your plugin for other projects with better fonts ;)

Le mar. 12 mars 2019 à 18:34, Kevin Gutowski <notifications@github.com> a
écrit :

**Comment by KevinGutowski** [comment]
Great to hear! Sorry that it can’t help with your font for now.
