### ISSUE TITLE
Panel not showing on second display

### ISSUE THREAD

**Issue by davidfuchsa** [KevinGutowski/betterTypePanel#25]
the panel works fine when I am using only my laptop screen (MBP 13 2016). When connected to the second display (38" - extended desktop) the panel does not show up. 

it also crashes the whole Sketch when I use a keyboard shortcut to toggle the panel. Can be also caused by other plugins clash?

**Comment by KevinGutowski** [comment]
Hiya @davidfuchsa! Sorry to hear that you are having troubles. I unfortunately can seem to reproduce the issue. If you could help me out in debugging I would greatly appreciate it!

You can do either of two things
1. Install the Sketch Dev Tools plugin https://github.com/skpm/sketch-dev-tools/releases
- Run this before running betterTypePanel

2. Open up the console app and search for "Sketch"
- Then run betterTypePanel

**Comment by KevinGutowski** [comment]
Actually, I think I figured out what is going wrong. I still can't reproduce the problem but I can try to do something else in my code that ensures things get closed properly. I'll push an update out tonight!

**Comment by KevinGutowski** [comment]
Just pushed an update. Let me know if it helped with things!

**Comment by davidfuchsa** [comment]
Hello, sorry for the late answer. 

I downloaded an update but I am still facing the same problem. There is a log from my console when I am trying to open the panel for a second time `ReferenceError: Can't find variable: HSMain
    at w (/Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool.sketchplugin/Contents/Sketch/my-command.js:1:11620)
    at default (/Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool.sketchplugin/Contents/Sketch/my-command.js:1:13197)
    at __skpm_run (/Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool.sketchplugin/Contents/Sketch/my-command.js:1:23799)
    at __skpm_run[native code] (/)`

Also it crashed when I used the sortcut. I am attaching a crash log if it will be of any help 

[crash log Sketch.txt](https://github.com/KevinGutowski/betterTypePanel/files/3467152/crash.log.Sketch.txt)

Can I help you in any other way?

**Comment by KevinGutowski** [comment]
Huh interesting… makes sense why the latest update wouldn’t help. But I’m still a little confused why you are getting that error.

Anywho, here is a modified version of my plugin that includes a lot more logging enabled. I also added a few extra checks to make sure that `HSMain` is defined 🤔 I you could install it and see if that fixes things/check the logs.

[bettertypetool-testing.sketchplugin.zip](https://github.com/KevinGutowski/betterTypePanel/files/3468496/bettertypetool-testing.sketchplugin.zip)

If this doesn’t work I’ll need to reach out to some other devs to get a better understanding of what is going on. Thanks for your help!

**Comment by KevinGutowski** [comment]
Hiya @davidfuchsa I believe I was able to fix this issue in the latest release (v0.3.3). Let me know if you run into any other problems!

https://github.com/KevinGutowski/betterTypePanel/releases/tag/v0.3.3
