### ISSUE TITLE
panel disappears after first use

### ISSUE THREAD

**Issue by mustafa-x** [KevinGutowski/betterTypePanel#26]
When I open sketch for the first time and set text using the panel everything is fine, but then I can no longer open the panel a second time. 

Steps to recreate bug;
Open panel
Close panel
Try to re open again.

**Comment by davidfuchsa** [comment]
I have the same issue. I tried to disable all other plugins, but the problem is still there.

**Comment by KevinGutowski** [comment]
Thanks for the issue ya'll (and sorry I missed this - need to change my notification settings…). I can't seem to reproduce the issue at the moment. If you are able to recreate and want to help, could you open up the console app and search for Sketch and let me know what you see there I would greatly appreciate it!

**Comment by KevinGutowski** [comment]
I just pushed an update that attempts to address this issue. Let me know if the bug has gone away!

**Comment by chadclark** [comment]
I am seeing the same issue with the latest update (0.3.1) and the latest version of Sketch.app (56.3).

They type panel appears after the first launch of Sketch.app (either by clicking in the menu screen or by using the keyboard command) and once closed, will not re-open (with both the menu or shortcut). You have to quit Sketch.app and re-open to make it appear once again.

Thanks for looking into this – it's such a wonderful plugin!

**Comment by chadclark** [comment]
Here is a Console messages I'm seeing when I first toggle the menu on:
```
ReferenceError: Can't find variable: HSMain
    at default (/Users/chad.clark/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool.sketchplugin/Contents/Sketch/my-command.js:1:23630)
    at __skpm_run (/Users/chad.clark/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool.sketchplugin/Contents/Sketch/my-command.js:1:23799)
    at __skpm_run[native code] (/)
```

and when I toggle it off:
```
ReferenceError: Can't find variable: HSMain
    at w (/Users/chad.clark/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool.sketchplugin/Contents/Sketch/my-command.js:1:11620)
    at /Users/chad.clark/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool.sketchplugin/Contents/Sketch/my-command.js:1:23218
```

**Comment by KevinGutowski** [comment]
Thanks @chadclark ! Apologies for the troubles - could you try installing this plugin here:

https://github.com/KevinGutowski/betterTypePanel/files/3468496/bettertypetool-testing.sketchplugin.zip

Its a modified version of my plugin that includes a lot more logging enabled. I also added a few extra checks to make sure that HSMain is defined 🤔 If you could install it and see if that fixes things/check the logs that would be really helpful.

**Comment by davidfuchsa** [comment]
Hello @KevinGutowski , the bug and crash after hitting the shortcut are still there. 

I am a complete noob to this console stuff and now there are many more logs. What exactly I am looking for? Can you look at the attached screenshot? 
<img width="744" alt="Screenshot 2019-08-07 at 18 17 20" src="https://user-images.githubusercontent.com/25434515/62639368-ab540800-b93f-11e9-9c6b-29bf30cf2bb5.png">

I am sending the ones that seem connected to the problem to me, but I am not sure you are looking for those.

1) ```❌ loadFramework: `HelloSketch` failed!: /Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/src. Please define HelloSketch_FrameworkPath if you're trying to @import in a custom plugin ```

2) ``` ReferenceError: Can't find variable: HSMain
    at closePanel (/Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing.sketchplugin/Contents/Sketch/my-command.js:1046:20)
    at runPanel (/Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing.sketchplugin/Contents/Sketch/my-command.js:206:15)
    at /Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing.sketchplugin/Contents/Sketch/my-command.js:128:11
    at __skpm_run (/Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing.sketchplugin/Contents/Sketch/my-command.js:1466:17)
    at __skpm_run[native code] (/) ```

Anyway thanks for looking into it. I appreciate that :)

**Comment by KevinGutowski** [comment]
Ah interesting! That’s exactly what I am looking for in the logs. Not sure why the framework isn’t loaded on close… very strange. Dang, if I was able to reproduce this issue I would be much better at debugging it! Nonetheless, I think its me being dumb and I just commented out this line of code on accident 

https://github.com/KevinGutowski/betterTypePanel/blob/master/src/my-command.js#L77

which is why `HelloSketch_FrameworkPath` isn’t defined 🤦‍♂️

I just uncommented that line of code - mind trying this one out?
[bettertypetool-testing.sketchplugin.zip](https://github.com/KevinGutowski/betterTypePanel/files/3478050/bettertypetool-testing.sketchplugin.zip)

**Comment by davidfuchsa** [comment]
@KevinGutowski Hello. Sry for the late response. Still not opening for the second time. But it's not crashing when I hit the keyboard shortcut :D. 

There are logs: 

`❌ loadFramework: `HelloSketch` failed!: /Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/src. Please define HelloSketch_FrameworkPath if you're trying to @import in a custom plugin`

`ReferenceError: Can't find variable: HSMain
    at closePanel (/Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing 2.sketchplugin/Contents/Sketch/my-command.js:1046:20)
    at runPanel (/Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing 2.sketchplugin/Contents/Sketch/my-command.js:206:15)
    at /Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing 2.sketchplugin/Contents/Sketch/my-command.js:128:11
    at __skpm_run (/Users/dejv/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing 2.sketchplugin/Contents/Sketch/my-command.js:1466:17)
    at __skpm_run[native code] (/)`

**Comment by julians** [comment]
Hello,
I’ve the same problem, here’s the log:

```
[Error] ReferenceError: Can't find variable: HSMain
	(anonyme Funktion) (/Users/julianstahnke/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing.sketchplugin/Contents/Sketch/my-command.js:137)
	__skpm_run (/Users/julianstahnke/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing.sketchplugin/Contents/Sketch/my-command.js:1466)
	__skpm_run
	JSObjectCallAsFunction
	-[Mocha callJSFunction:withArgumentsInArray:]
	-[Mocha callJSFunctionWithName:withArgumentsInArray:]
	-[Mocha callFunctionWithName:withArgumentsInArray:]
	-[COScript callFunctionNamed:withArguments:]
	-[MSPluginCommand runHandler:withOptionalKey:context:manager:onComplete:]
	-[MSPluginCommand runHandlerWithKey:context:manager:onComplete:]
	-[MSPluginCommand run:manager:onComplete:]
	?
	-[MSActionController(ActionObserving) performFakeActionWithID:context:block:]
	?
	?
	?
	-[MSAction performAction:]
	-[NSApplication(NSResponder) sendAction:to:from:]
	-[NSMenuItem _corePerformAction]
	-[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:]
	-[NSMenu performActionForItemAtIndex:]
	-[NSMenu _internalPerformActionForItemAtIndex:]
	-[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:]
	NSSLMMenuEventHandler
	DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*)
	SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*)
	SendEventToEventTarget
	SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**)
	SendMenuCommandWithContextAndModifiers
	SendMenuItemSelectedEvent
	FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*)
	MenuSelectCore(MenuData*, Point, double, unsigned int, OpaqueMenuRef**, unsigned short*)
	_HandleMenuSelection2
	_NSHandleCarbonMenuEvent
[Error] ReferenceError: Can't find variable: HSMain
	closePanel (/Users/julianstahnke/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing.sketchplugin/Contents/Sketch/my-command.js:1046)
	(anonyme Funktion) (/Users/julianstahnke/Library/Application Support/com.bohemiancoding.sketch3/Plugins/bettertypetool-testing.sketchplugin/Contents/Sketch/my-command.js:600)
	JSObjectCallAsFunction
	-[Mocha callJSFunction:withArgumentsInArray:]
	-[COScript callJSFunction:withArgumentsInArray:]
	-[COSTarget callAction:]
	-[NSApplication(NSResponder) sendAction:to:from:]
	-[NSControl sendAction:to:]
	__26-[NSCell _sendActionFrom:]_block_invoke
	-[NSCell _sendActionFrom:]
	-[NSButtonCell _sendActionFrom:]
	-[NSCell trackMouse:inRect:ofView:untilMouseUp:]
	-[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:]
	-[NSControl mouseDown:]
	-[_NSThemeWidget mouseDown:]
	-[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:]
	-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]
	-[NSWindow(NSEventRouting) sendEvent:]
	-[NSApplication(NSEvent) sendEvent:]
	-[NSApplication run]
	NSApplicationMain
	start
	?
```

**Comment by KevinGutowski** [comment]
I’m able to reproduce the issue now and the recent release v0.3.3 should resolve this! Thanks for everyone’s help!

https://github.com/KevinGutowski/betterTypePanel/releases/tag/v0.3.3
